### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by clly** [Succo/hhvm-datadog#1]
All code unless otherwise specified is "All Rights Reserved". People wouldn't be able to use this code in a different project unless you add a LICENSE.

If this is by design your LICENSE could just say all rights reserved.

**Comment by Succo** [comment]
Yeah it's something I wanted to do and kind of forgot.

I added an MIT license file.

BTW I'm curious as I created this just to experiment and play around myself, do you plan on using this anywhere?

**Comment by clly** [comment]
I was hoping to :) I did something similar for threads yesterday. I'll open
pull request today
